server:
  port: 8080
  #address: 0.0.0.0

spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

          routes:
            - id: user-service
              uri: lb://USER-SERVICE
              predicates:
                - Path=/auth/**
              #filters:
               # - StripPrefix=1   
                     
            - id: order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/internal/v1/orders/**
             # filters:
              #  - StripPrefix=1
                
            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/internal/v1/payment/**
                
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10   # tokens per second
                    redis-rate-limiter.burstCapacity: 20
                    key-resolver: "#{@userAndRouteKeyResolver}"
             

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379} 
  
  security:
    oauth2:
      resourceserver:
        jwt:
          # For HS256 demo. In prod, prefer JWK set URI / public key.
          secret-key: MysuperSecretKeyForJWT1234567890098765432dffgdfsgfgsfgsdfgfsfgffgsfg456w5w465w4rggfg4453


