spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/servicepayment
    username: grantjvm_market_shop1
    password: NAmyVH7hvN22tzd3MYND
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
        format_sql: true
  cloud:
    compatibility-verifier:
      enabled: false
   
  kafka:
   bootstrap-servers: localhost:9092
   producer:
     key-serializer: org.apache.kafka.common.serialization.StringSerializer
     value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
   consumer:
     key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
     value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
     group-id: order-group
     properties:
       spring.json.trusted.packages: "*"


app:
  kafka:
    topic: orders-topic

custom:
 msg: for my thrid message  
 
payment:
  service.url : http://localhost:8081/ 
  
  
server:
 port: 8082
