spring:
  application:
    name: order-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/servicepayment
    username: grantjvm_market_shop1
    password: NAmyVH7hvN22tzd3MYND
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
        format_sql: true
  cloud:
    compatibility-verifier:
      enabled: false
    config:
      override-none: true  
   
  web:
    cors:
      allowed-origins: none    
    
    
  kafka:
   bootstrap-servers: localhost:9092
   consumer:
     group-id: order-service
     key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
     value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
     properties:
       spring.json.trusted.packages: com.microtest.event
   producer:
     key-serializer: org.apache.kafka.common.serialization.StringSerializer
     value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
 

app:
  kafka:
    topic:
      order: orders-topic3
      partition: 3
      replicate: 1
    dlt:
      order: orders-topic3.DLT
      partition: 3
      replicate: 1  
      
      
   

custom:
 msg: for my thrid message  
 
payment:
  service.url : http://localhost:8081/ 
  
  
server:
 port: 8082
