spring:
  application:
    name: payment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/servicepayment
    username: grantjvm_market_shop1
    password: NAmyVH7hvN22tzd3MYND
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
       format_sql: true

  cloud:
    compatibility-verifier:
      enabled: false
         
  kafka:
    consumer:
      group-id: payment-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest
      properties:
        spring:
         json:
          #value:
           #default:
            #type: com.microtest.PaymentService.dto.OrderEvent
          trusted:
           packages: "*"
         deserializer:
          key:
           delegate:
            class: org.apache.kafka.common.serialization.StringDeserializer
          value:
           delegate:
            class: org.springframework.kafka.support.serializer.JsonDeserializer
	  use:
	   type:
	    headers: false



server:
  port: 8081



