spring:
  application:
    name: payment-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/servicepayment
    username: grantjvm_market_shop1
    password: NAmyVH7hvN22tzd3MYND
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
       format_sql: true

  cloud:
    compatibility-verifier:
      enabled: false
    config:
      override-none: true   
      
  #web:
   # cors:
    #  allowed-origins: none      
    
  security:
    oauth2:
      resourceserver:
        jwt:
          # For HS256 demo. In prod, prefer JWK set URI / public key.
          secret-key: MysuperSecretKeyForJWT1234567890098765432dffgdfsgfgsfgsdfgfsfgffgsfg456w5w465w4rggfg4453
    

  kafka:
   bootstrap-servers: localhost:9092
   consumer:
     group-id: payment-service
     key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
     value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
     properties:
       spring.json.trusted.packages: com.microtest.event
   producer:
     key-serializer: org.apache.kafka.common.serialization.StringSerializer
     value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
   


app:
  kafka:
    topic:
      order: orders-topic3
      ordercreate: orders-create
      partition: 3
      replicate: 1
      paymentSuccess: payment-succed
      paymentFailed: payment-failed
    dlt:
      order: orders-topic3.DLT
      ordercreate: orders-create.DLT
      partition: 3
      replicate: 1  
    


server:
  port: 8081



