spring:
  application:
    name: user-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:/data/user-db
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.H2Dialect
     
  
   


eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/


      
      
