spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.1:3306/serviceorder
    username: rootdocker
    password: 12Dinfoyoune
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
       format_sql: true
  
   


eureka:
  client:
    service-url:
      defaultZone: http://eureka:8761/eureka/



